app = "viral-views-app"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  DATABASE_URL = "file:./db/production.sqlite"
  SENDGRID_API_KEY = "your_sendgrid_key"
  JWT_SECRET = "your_jwt_secret"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
