# DigitalOcean App Platform spec for Viral Views
name: viral-views-app
region: nyc
services:
  - name: web
    dockerfile_path: ./Dockerfile
    github:
      repo: AnonymousEne/viral-views-official1
      branch: main
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        value: file:./db/production.sqlite
      - key: SENDGRID_API_KEY
        value: "your_sendgrid_key"
      - key: JWT_SECRET
        value: "your_jwt_secret"
    http_port: 3000
    routes:
      - path: /
        preserve_path_prefix: true
    health_check:
      http_path: /api/health
    run_command: "npm run start"
    instance_count: 1
    instance_size_slug: basic-xxs
